version: '3.8'

services:
  client:
    build: ./client
    depends_on:
      - server
    volumes:
      - client_build:/app/dist

  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - client_build:/dist:/usr/share/nginx/html

  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: